[package]
name = "r8"
version = "0.1.0"
authors = ["Julien Doutre <jul.doutre@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
piston_window = "0.98.0"
piston2d-graphics = "0.35.0"

[lib]
r8 = {path = "src/lib.rs"}
