name: Rust
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    needs: [tests]
    if: ${{ base_ref == "master" }}
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.0
